server:
  port: 8082
spring:
  application:
    name: demo-provider
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: ${eureka:http://192.168.0.152:1111/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'