server:
  port: 8081

spring:
  application:
    name: consumer
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: https://cse.cn-north-4.myhuaweicloud.com:443
        version: 0.0.1
        healthCheckInterval: 30
      config:
        address: https://cse.cn-north-4.myhuaweicloud.com:443
      credentials:
        accessKey: yourak
        secretKey: yoursk
        project: cn-north-4
        akskCustomCipher: default